import { Patient, Document, TestResult, Conflict } from "./types";
import { computeTestStatus } from "./referenceRangeEngine";

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "pat-101",
    name: "Eleanor Vance",
    age: 62,
    sex: "Female",
    symptoms: "Fatigue, mild morning dizziness, increased thirst over past 3 months",
    conditions: "Type 2 Diabetes Mellitus, Essential Hypertension, Dyslipidemia",
    allergies: "Penicillin (rash), Sulfa drugs (hives)",
    medications: "Metformin 1000mg BID, Lisinopril 20mg QD, Atorvastatin 20mg QD",
    source: "user_provided",
  },
  {
    id: "pat-102",
    name: "Marcus Chen",
    age: 45,
    sex: "Male",
    symptoms: "Periodic joint soreness in bilateral hands and right big toe, afternoon lethargy",
    conditions: "Hyperuricemia with gout history, Mild Osteoarthritis",
    allergies: "No known drug allergies (NKDA)",
    medications: "Allopurinol 100mg QD, Naproxen 500mg PRN (during flare)",
    source: "user_provided",
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "doc-101-1",
    patient_id: "pat-101",
    filename: "Quest_CMP_LipidPanel_2024_03.pdf",
    upload_date: "2024-03-15",
    document_type: "Comprehensive Metabolic Panel & Lipid Panel",
    document_date: "2024-03-12",
    laboratory: "Quest Diagnostics - Metro Region",
  },
  {
    id: "doc-101-2",
    patient_id: "pat-101",
    filename: "LabCorp_Endo_Followup_2024_08.pdf",
    upload_date: "2024-08-20",
    document_type: "Endocrine & Glycemic Follow-up",
    document_date: "2024-08-18",
    laboratory: "LabCorp Burlington Reference Lab",
  },
  {
    id: "doc-102-1",
    patient_id: "pat-102",
    filename: "BioReference_CBC_Inflammatory_2024_02.pdf",
    upload_date: "2024-02-10",
    document_type: "Complete Blood Count & Inflammatory Panel",
    document_date: "2024-02-08",
    laboratory: "BioReference Laboratories",
  },
  {
    id: "doc-102-2",
    patient_id: "pat-102",
    filename: "Quest_Renal_Liver_2024_07.pdf",
    upload_date: "2024-07-25",
    document_type: "Renal Function & Liver Enzymes",
    document_date: "2024-07-22",
    laboratory: "Quest Diagnostics - Bay Area",
  },
];

// Raw test entries before pure engine status computation
const rawResults = [
  // Patient 1 - Document 1 (Quest Diagnostics 2024-03-12)
  {
    id: "res-101-1",
    document_id: "doc-101-1",
    test_name: "Glucose (Fasting)",
    value: "142",
    unit: "mg/dL",
    reference_min: 70,
    reference_max: 99,
    reference_raw_text: "70 - 99 mg/dL",
    source_snippet: "GLUCOSE, FASTING: 142 mg/dL (Ref: 70 - 99 mg/dL) [HIGH]",
    confidence: 0.98,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "142",
  },
  {
    id: "res-101-2",
    document_id: "doc-101-1",
    test_name: "Hemoglobin A1c",
    value: "7.8",
    unit: "%",
    reference_min: null,
    reference_max: 5.6,
    reference_raw_text: "< 5.7 %",
    source_snippet: "HEMOGLOBIN A1c: 7.8 % (Ref: < 5.7 %) [HIGH]",
    confidence: 0.99,
    provenance: "document_extracted" as const,
    verification_status: "verified" as const,
    original_ai_value: "7.8",
  },
  {
    id: "res-101-3",
    document_id: "doc-101-1",
    test_name: "Total Cholesterol",
    value: "215",
    unit: "mg/dL",
    reference_min: null,
    reference_max: 199,
    reference_raw_text: "< 200 mg/dL",
    source_snippet: "CHOLESTEROL, TOTAL: 215 mg/dL (Desirable: < 200 mg/dL)",
    confidence: 0.95,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "215",
  },
  {
    id: "res-101-4",
    document_id: "doc-101-1",
    test_name: "HDL Cholesterol",
    value: "48",
    unit: "mg/dL",
    reference_min: 50,
    reference_max: null,
    reference_raw_text: "> 50 mg/dL",
    source_snippet: "HDL CHOLESTEROL: 48 mg/dL (Ref: > 50 mg/dL) [LOW]",
    confidence: 0.96,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "48",
  },
  {
    id: "res-101-5",
    document_id: "doc-101-1",
    test_name: "LDL Cholesterol",
    value: "128",
    unit: "mg/dL",
    reference_min: null,
    reference_max: 99,
    reference_raw_text: "< 100 mg/dL",
    source_snippet: "LDL CHOLESTEROL (CALC): 128 mg/dL (Optimal: < 100 mg/dL)",
    confidence: 0.94,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "128",
  },
  {
    id: "res-101-6",
    document_id: "doc-101-1",
    test_name: "Serum Creatinine",
    value: "0.90",
    unit: "mg/dL",
    reference_min: 0.5,
    reference_max: 1.1,
    reference_raw_text: "0.50 - 1.10 mg/dL",
    source_snippet: "CREATININE: 0.90 mg/dL (Ref: 0.50 - 1.10 mg/dL)",
    confidence: 0.99,
    provenance: "document_extracted" as const,
    verification_status: "verified" as const,
    original_ai_value: "0.90",
  },
  {
    id: "res-101-7",
    document_id: "doc-101-1",
    test_name: "Potassium",
    value: "4.4",
    unit: "mmol/L",
    reference_min: 3.5,
    reference_max: 5.1,
    reference_raw_text: "3.5 - 5.1 mmol/L",
    source_snippet: "POTASSIUM: 4.4 mmol/L (Ref: 3.5 - 5.1 mmol/L)",
    confidence: 0.98,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "4.4",
  },

  // Patient 1 - Document 2 (LabCorp 2024-08-18)
  {
    id: "res-101-8",
    document_id: "doc-101-2",
    test_name: "Glucose (Fasting)",
    value: "118",
    unit: "mg/dL",
    reference_min: 70,
    reference_max: 99,
    reference_raw_text: "70 - 99 mg/dL",
    source_snippet: "Fasting Blood Glucose: 118 mg/dL [H] (Ref Range: 70-99)",
    confidence: 0.97,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "118",
  },
  {
    id: "res-101-9",
    document_id: "doc-101-2",
    test_name: "Hemoglobin A1c",
    value: "7.1",
    unit: "%",
    reference_min: null,
    reference_max: 5.6,
    reference_raw_text: "< 5.7 %",
    source_snippet: "HbA1c Glycated Hemoglobin: 7.1 % (Reference: < 5.7 %)",
    confidence: 0.99,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "7.1",
  },
  {
    id: "res-101-10",
    document_id: "doc-101-2",
    test_name: "Serum Creatinine",
    value: "0.85",
    unit: "mg/dL",
    reference_min: 0.5,
    reference_max: 1.1,
    reference_raw_text: "0.50 - 1.10 mg/dL",
    source_snippet: "Creatinine, Serum: 0.85 mg/dL (Ref: 0.50-1.10)",
    confidence: 0.99,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "0.85",
  },
  {
    id: "res-101-11",
    document_id: "doc-101-2",
    test_name: "Vitamin D, 25-Hydroxy",
    value: "22",
    unit: "ng/mL",
    reference_min: 30,
    reference_max: 100,
    reference_raw_text: "30.0 - 100.0 ng/mL",
    source_snippet: "Vitamin D, 25-Hydroxy: 22.0 ng/mL (Ref: 30.0 - 100.0 ng/mL) [LOW]",
    confidence: 0.94,
    provenance: "document_extracted" as const,
    verification_status: "edited" as const,
    original_ai_value: "20",
  },

  // Patient 2 - Document 1 (BioReference 2024-02-08)
  {
    id: "res-102-1",
    document_id: "doc-102-1",
    test_name: "White Blood Cell (WBC)",
    value: "7.2",
    unit: "x10^3/uL",
    reference_min: 4.5,
    reference_max: 11.0,
    reference_raw_text: "4.5 - 11.0 x10^3/uL",
    source_snippet: "WBC Count: 7.2 x10^3/uL (Reference: 4.5 - 11.0)",
    confidence: 0.99,
    provenance: "document_extracted" as const,
    verification_status: "verified" as const,
    original_ai_value: "7.2",
  },
  {
    id: "res-102-2",
    document_id: "doc-102-1",
    test_name: "Hemoglobin",
    value: "15.4",
    unit: "g/dL",
    reference_min: 13.5,
    reference_max: 17.5,
    reference_raw_text: "13.5 - 17.5 g/dL",
    source_snippet: "Hemoglobin: 15.4 g/dL (Reference: 13.5 - 17.5)",
    confidence: 0.98,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "15.4",
  },
  {
    id: "res-102-3",
    document_id: "doc-102-1",
    test_name: "C-Reactive Protein (CRP)",
    value: "4.8",
    unit: "mg/L",
    reference_min: null,
    reference_max: 3.0,
    reference_raw_text: "< 3.0 mg/L",
    source_snippet: "C-Reactive Protein (CRP): 4.8 mg/L [HIGH] (Ref: < 3.0 mg/L)",
    confidence: 0.96,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "4.8",
  },
  {
    id: "res-102-4",
    document_id: "doc-102-1",
    test_name: "Uric Acid",
    value: "8.4",
    unit: "mg/dL",
    reference_min: 3.5,
    reference_max: 7.2,
    reference_raw_text: "3.5 - 7.2 mg/dL",
    source_snippet: "URIC ACID, SERUM: 8.4 mg/dL (Ref: 3.5 - 7.2 mg/dL) [HIGH]",
    confidence: 0.97,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "8.4",
  },

  // Patient 2 - Document 2 (Quest Diagnostics 2024-07-22)
  {
    id: "res-102-5",
    document_id: "doc-102-2",
    test_name: "Uric Acid",
    value: "6.8",
    unit: "mg/dL",
    reference_min: 3.5,
    reference_max: 7.2,
    reference_raw_text: "3.5 - 7.2 mg/dL",
    source_snippet: "Uric Acid, Serum: 6.8 mg/dL (Ref: 3.5 - 7.2 mg/dL)",
    confidence: 0.98,
    provenance: "document_extracted" as const,
    verification_status: "verified" as const,
    original_ai_value: "6.8",
  },
  {
    id: "res-102-6",
    document_id: "doc-102-2",
    test_name: "ALT (SGPT)",
    value: "32",
    unit: "U/L",
    reference_min: 9,
    reference_max: 46,
    reference_raw_text: "9 - 46 U/L",
    source_snippet: "ALT (SGPT): 32 U/L (Reference: 9 - 46 U/L)",
    confidence: 0.97,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "32",
  },
  {
    id: "res-102-7",
    document_id: "doc-102-2",
    test_name: "AST (SGOT)",
    value: "28",
    unit: "U/L",
    reference_min: 10,
    reference_max: 40,
    reference_raw_text: "10 - 40 U/L",
    source_snippet: "AST (SGOT): 28 U/L (Reference: 10 - 40 U/L)",
    confidence: 0.97,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "28",
  },
  {
    id: "res-102-8",
    document_id: "doc-102-2",
    test_name: "Blood Urea Nitrogen (BUN)",
    value: "16",
    unit: "mg/dL",
    reference_min: 7,
    reference_max: 20,
    reference_raw_text: "7 - 20 mg/dL",
    source_snippet: "Blood Urea Nitrogen (BUN): 16 mg/dL (Ref: 7 - 20)",
    confidence: 0.96,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "16",
  },
  {
    id: "res-102-9",
    document_id: "doc-102-2",
    test_name: "Rheumatoid Factor",
    value: "10",
    unit: "IU/mL",
    reference_min: null,
    reference_max: 14,
    reference_raw_text: "< 14 IU/mL",
    source_snippet: "Rheumatoid Factor: 10 IU/mL (Reference: < 14 IU/mL)",
    confidence: 0.91,
    provenance: "document_extracted" as const,
    verification_status: "unverified" as const,
    original_ai_value: "10",
  },
];

// Compute status strictly using the deterministic pure function per Rule 1
export const MOCK_TEST_RESULTS: TestResult[] = rawResults.map((res) => ({
  ...res,
  status: computeTestStatus(res.value, res.reference_min, res.reference_max),
}));

export const MOCK_CONFLICTS: Conflict[] = [
  {
    id: "conf-1",
    field_name: "Uric Acid",
    value_a: "8.4 mg/dL",
    source_a: "BioReference (2024-02-08)",
    value_b: "6.8 mg/dL",
    source_b: "Quest Diagnostics (2024-07-22)",
    resolved: false,
  },
  {
    id: "conf-2",
    field_name: "Allergies",
    value_a: "Penicillin, Sulfa",
    source_a: "Intake Questionnaire (2024-03-01)",
    value_b: "No Known Drug Allergies (NKDA)",
    source_b: "Quest Document Header (2024-03-12)",
    resolved: true,
  },
];
